stages:
  - test
  - prepare
  - deploy

# Cache gems in between builds
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/ruby
    - vendor/jruby

variables:
  BUNDLE_JOBS: 10
  BUNDLE_PATH: vendor
  CI: 1

.before_script: &before_script
  - ruby -v
  - bundle install

.test: &test
- bundle exec rake


jruby:
  variables:
    JRUBY_OPTS: "--debug"
  before_script: *before_script
  image: "jruby:9.4"
  script:
    - *test
  artifacts:
    paths:
      - coverage
truffleruby:
  allow_failure: true
  before_script:
    - *before_script
  image: "ghcr.io/graalvm/truffleruby:latest"
  script:
    - *test
  allow_failure: true
  artifacts:
    paths:
      - "coverage"
ruby27:
  before_script:
    - *before_script
  image: "ruby:2.7"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby30:
  before_script:
    - *before_script
    - export RUBYOPT="-rbundler/setup -rrbs/test/setup"
    - export RBS_TEST_RAISE="true"
    - export RBS_TEST_LOGLEVEL="error"
    - export RBS_TEST_OPT="-Isig -rbase64"
    - export RBS_TEST_TARGET="HTTP2Next*"
  image: "ruby:3.0"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby31:
  before_script:
    - *before_script
    - export RUBYOPT="-rbundler/setup -rrbs/test/setup"
    - export RBS_TEST_RAISE="true"
    - export RBS_TEST_LOGLEVEL="error"
    - export RBS_TEST_OPT="-Isig -rbase64"
    - export RBS_TEST_TARGET="HTTP2Next*"
  image: "ruby:3.1"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby32:
  before_script:
    - *before_script
    - export RUBYOPT="-rbundler/setup -rrbs/test/setup"
    - export RBS_TEST_RAISE="true"
    - export RBS_TEST_LOGLEVEL="error"
    - export RBS_TEST_OPT="-Isig -rbase64"
    - export RBS_TEST_TARGET="HTTP2Next*"
  image: "ruby:3.2"
  script:
    - *test
  artifacts:
    paths:
      - coverage

coverage:
  stage: prepare
  image: "ruby:3.2"
  before_script:
    - gem install simplecov --no-doc
  script:
    - find coverage -name "*resultset.json" -exec sed -i 's?/home?'`pwd`'?' {} \;
    - rake coverage:report
  artifacts:
    paths:
      - "coverage/"

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir public
    - mv coverage public/coverage
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 30 days
