# Cache gems in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - vendor/jruby

.before_script: &before_script
  - ruby -v
  - bundle install -j 4 --path vendor

.test: &test
- bundle exec rake


jruby:
  variables:
    CI: 1
    JRUBY_OPTS: "--debug"
  before_script: *before_script
  image: "jruby:9.2.9"
  script:
    - *test
ruby21:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.1"
  script:
    - *test
ruby22:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.2"
  only:
    - master
  script:
    - *test
ruby23:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.3"
  only:
    - master
  script:
    - *test
ruby24:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.4"
  only:
    - master
  script:
    - *test
ruby25:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.5"
  only:
    - master
  script:
    - *test
ruby26:
  variables:
    CI: 1
  before_script:
    - *before_script
  image: "ruby:2.6"
  script:
    - *test



