stages:
  - test
  - prepare
  - deploy

# Cache gems in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - vendor/jruby

variables:
  BUNDLE_JOBS: 10
  BUNDLE_PATH: vendor
  CI: 1

.before_script: &before_script
  - ruby -v
  - bundle install

.test: &test
- bundle exec rake


jruby:
  variables:
    JRUBY_OPTS: "--debug"
  before_script: *before_script
  image: "jruby:9.2.9"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby21:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.1-alpine"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby22:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.2-alpine"
  only:
    - master
  script:
    - *test
ruby23:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.3-alpine"
  only:
    - master
  script:
    - *test
ruby24:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.4-alpine"
  only:
    - master
  script:
    - *test
ruby25:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.5-alpine"
  only:
    - master
  script:
    - *test
ruby26:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.6-alpine"
  only:
    - master
  script:
    - *test
ruby27:
  before_script:
    - apk --update add g++ make
    - *before_script
  image: "ruby:2.7-alpine"
  script:
    - *test
  artifacts:
    paths:
      - coverage
ruby30:
  before_script:
    - apk --update add g++ make git
    - *before_script
    - export RUBYOPT="-rbundler/setup -rrbs/test/setup"
    - export RBS_TEST_RAISE="true"
    - export RBS_TEST_LOGLEVEL="error"
    - export RBS_TEST_OPT="-Isig"
    - export RBS_TEST_TARGET="HTTP2Next*"
  image: "ruby:3.0-rc-alpine"
  script:
    - *test
  artifacts:
    paths:
      - coverage

coverage:
  stage: prepare
  dependencies:
    - jruby
    - ruby21
    - ruby27
  image: "ruby:2.7-alpine"
  before_script:
    - apk --update add g++ make
    - gem install simplecov --no-doc
  script:
    - find coverage -name "*resultset.json" -exec sed -i 's?/home?'`pwd`'?' {} \;
    - rake coverage:report
  artifacts:
    paths:
      - "coverage/"

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir public
    - mv coverage public/coverage
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 30 days
