inherit_from: .rubocop.yml

# Because this cop doesn't work well with frozen regexes
Style/RedundantFreeze:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Layout/IndentHeredoc:
  Exclude:
    - "lib/tasks/generate_huffman_table.rb"
    - "example/*"

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/LineLength:
  Max: 128

Style/BracesAroundHashParameters:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile
