inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**'
    - 'vendor/**/*'
    - '**/huffman_statemachine.rb'

Metrics/LineLength:
  Max: 120

Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/IndentHash:
  EnforcedStyle: consistent

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/SpaceAroundOperators:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false
