inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/*'

Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/IndentHash:
  EnforcedStyle: consistent

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
