inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "bin/**"
    - "vendor/**/*"
    - "**/huffman_statemachine.rb"


Metrics/BlockLength:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false



