inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "bin/**"
    - "vendor/**/*"
    - "**/huffman_statemachine.rb"

Layout/IndentHeredoc:
  Exclude:
    - "lib/tasks/generate_huffman_table.rb"
    - "example/*"

Metrics/LineLength:
  Max: 121

Metrics/BlockLength:
  Max: 720

Naming/UncommunicativeMethodParamName:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false



