inherit_from: .rubocop.yml

# TODO: remove this if min supported version of ruby is 2.3
Style/HashSyntax:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/HeredocIndentation:
  Exclude:
    - "lib/tasks/generate_huffman_table.rb"
    - "example/*"

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 128

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - Rakefile

RescueEnsureAlignment:
  Enabled: false
