module HTTP2Next
  class Connection
    include FlowBuffer
    include Emitter
    include Error

    REQUEST_MANDATORY_HEADERS: Array[String]
    RESPONSE_MANDATORY_HEADERS: Array[String]

    attr_reader state: Symbol

    attr_reader local_window: Integer
    attr_reader remote_window: Integer

    alias window local_window

    attr_reader remote_settings: settings_hash
    attr_reader local_settings: settings_hash
    attr_reader pending_settings: settings_ary

    attr_reader active_stream_count: Integer

    attr_writer max_streams: Integer?

    @stream_id: Integer
    @local_role: :client | :server
    @remote_role: :client | :server

    @compressor: Header::Compressor
    @decompressor: Header::Decompressor

    @last_activated_stream: Integer
    @last_stream_id: Integer
    @streams: Hash[Integer, Stream]
    @streams_recently_closed: Hash[Integer, Stream]

    @framer: Framer

    @local_window_limit: Integer
    @local_window: Integer
    @remote_window_limit: Integer
    @remote_window: Integer

    @recv_buffer: String
    @continuation: Array[frame]
    @error: Symbol?

    @h2c_upgrade: Symbol?
    @closed_since: (Float | Integer)?
    @received_frame: bool

    def closed?: () -> bool

    def new_stream: (**untyped) -> Stream

    def ping: (String) -> void
            | (String) { (*untyped) -> void } -> void

    def goaway: (?Symbol, ?String) -> void

    def window_update: (Integer increment) -> void

    def settings: (settings_enum) -> void

    def receive: (string data) -> void
    alias << receive

    private

    def initialize: (?settings_hash) -> untyped

    def send: (frame) -> void

    def encode: (frame) -> Array[String]

    def connection_frame?: (frame) -> bool

    def connection_management: (frame) -> void

    def ping_management: (frame) -> void

    def validate_settings: (:client | :server, settings_enum) -> void

    def connection_settings: (frame) -> void

    def decode_headers: (frame) -> void

    def encode_headers: (frame) -> Array[frame]

    def activate_stream: (id: Integer, **untyped) -> Stream

    def verify_stream_order: (Integer id) -> void

    def verify_pseudo_headers: (frame) -> void

    def _verify_pseudo_headers: (frame, Array[String]) -> void

    def connection_error: (?Symbol error, ?msg: String, ?e: StandardError) -> void
  end
end