module HTTP2Next
  module Header
    type header_key = :type | :name | :value | :index
    type header_value = Integer | String | :indexed | :changetablesize | :incremental | :noindex | :neverindexed

    #type context_hash = {
    #  huffman?: (:always | :never | :shorter),
    #  index?: (:all | :static | :never),
    #  table_size?: Integer
    #}
    type context_hash = Hash[Symbol, Symbol | Integer]

    type header_command = Hash[header_key, header_value]
  end
end
